# Dummy data for testing the website:

products = [
    {
        'id': '1',
        'name': 'Some Product',
        'image': '',
        'description': 'Product Description',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 199.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'id': '2',
        'name': 'Some Product',
        'image': '',
        'description': 'Product Description',
        'brand': 'Microsoft',
        'category': 'OS',
        'price': 75.99,
        'countInStock': 10,
        'rating': 3.2,
        'numReviews': 25,
    },
    {
        'id': '3',
        'name': 'Some Product',
        'image': '',
        'description': 'Product Description',
        'brand': 'Google',
        'category': 'Software',
        'price': 199.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 31,
    },
    {
        'id': '4',
        'name': 'Some Product',
        'image': '',
        'description': 'Product Description',
        'brand': 'Amazon',
        'category': 'Service',
        'price': 12.99,
        'countInStock': 10,
        'rating': 5.0,
        'numReviews': 12,
    },
]